## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [5]:
from sklearn.model_selection import train_test_split,KFold
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [10]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X[:40,], y[:40], test_size=0.5, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X[40:,], y[40:], test_size=0.125, random_state=42)
X_train2

array([[575, 576, 577, 578, 579],
       [290, 291, 292, 293, 294],
       [260, 261, 262, 263, 264],
       [245, 246, 247, 248, 249],
       [355, 356, 357, 358, 359],
       [955, 956, 957, 958, 959],
       [685, 686, 687, 688, 689],
       [480, 481, 482, 483, 484],
       [855, 856, 857, 858, 859],
       [720, 721, 722, 723, 724],
       [880, 881, 882, 883, 884],
       [590, 591, 592, 593, 594],
       [500, 501, 502, 503, 504],
       [775, 776, 777, 778, 779],
       [210, 211, 212, 213, 214],
       [815, 816, 817, 818, 819],
       [425, 426, 427, 428, 429],
       [410, 411, 412, 413, 414],
       [545, 546, 547, 548, 549],
       [650, 651, 652, 653, 654],
       [330, 331, 332, 333, 334],
       [890, 891, 892, 893, 894],
       [610, 611, 612, 613, 614],
       [680, 681, 682, 683, 684],
       [930, 931, 932, 933, 934],
       [380, 381, 382, 383, 384],
       [605, 606, 607, 608, 609],
       [310, 311, 312, 313, 314],
       [915, 916, 917, 918, 919],
       [535, 5

In [14]:
X_test=np.concatenate((X_test1,X_test2), axis=0)
y_test=np.concatenate((y_test1,y_test2), axis=0)
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])